Repository 9oormthon-univ/2024_DANPOONG_TEAM_51_BE, pull requests merged in 2024-11, with the labels that each got.

#3 [FEAT] 패키지 구조 분리 및 glabal 패키지 구현
  src/main/java/com/cone/cone/domain/mentorings/dummy.txt
  src/main/java/com/cone/cone/domain/messages/dummy.txt
  src/main/java/com/cone/cone/domain/room/dummy.txt
  src/main/java/com/cone/cone/domain/user/dummy.txt
  src/main/java/com/cone/cone/global/base/BaseTime.java
  src/main/java/com/cone/cone/global/code/CommonExceptionCode.java
  src/main/java/com/cone/cone/global/code/ExceptionCode.java
  src/main/java/com/cone/cone/global/code/SuccessCode.java
  src/main/java/com/cone/cone/global/exception/CustomException.java
  src/main/java/com/cone/cone/global/exception/GlobalExceptionHandler.java
  src/main/java/com/cone/cone/global/response/ResponseTemplate.java
Labels: 🌱 Feat, 🍀 성은

#10 [FEAT] 멘토링 방 API 구현
  src/main/java/com/cone/cone/domain/messages/dummy.txt
  src/main/java/com/cone/cone/domain/messages/entity/Message.java
  src/main/java/com/cone/cone/domain/room/code/RoomExceptionCode.java
  src/main/java/com/cone/cone/domain/room/code/RoomSuccessCode.java
  src/main/java/com/cone/cone/domain/room/controller/RoomApi.java
  src/main/java/com/cone/cone/domain/room/controller/RoomController.java
  src/main/java/com/cone/cone/domain/room/dto/RoomCreateRequest.java
  src/main/java/com/cone/cone/domain/room/dummy.txt
  src/main/java/com/cone/cone/domain/room/entity/Room.java
  src/main/java/com/cone/cone/domain/room/repository/RoomRepository.java
  src/main/java/com/cone/cone/domain/room/service/RoomService.java
  src/main/java/com/cone/cone/domain/room/service/RoomServiceImpl.java
  src/main/java/com/cone/cone/domain/user/code/MenteeExceptionCode.java
  src/main/java/com/cone/cone/domain/user/code/MentorExceptionCode.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeApi.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeController.java
  src/main/java/com/cone/cone/domain/user/controller/MentorApi.java
  src/main/java/com/cone/cone/domain/user/controller/MentorController.java
  src/main/java/com/cone/cone/domain/user/entity/User.java
  src/main/java/com/cone/cone/domain/user/repository/MenteeRepository.java
  src/main/java/com/cone/cone/domain/user/repository/MentorRepository.java
Labels: 🌱 Feat, 🌱 송목

#14 [FEAT] 온보딩 API 구현
  src/main/java/com/cone/cone/domain/auth/code/AuthSuccessCode.java
  src/main/java/com/cone/cone/domain/auth/controller/AuthApi.java
  src/main/java/com/cone/cone/domain/auth/controller/AuthController.java
  src/main/java/com/cone/cone/domain/auth/service/AuthService.java
  src/main/java/com/cone/cone/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/cone/cone/domain/auth/service/SessionService.java
  src/main/java/com/cone/cone/domain/auth/service/SessionServiceImpl.java
  src/main/java/com/cone/cone/domain/user/controller/AuthController.java
  src/main/java/com/cone/cone/domain/user/controller/MentorApi.java
  src/main/java/com/cone/cone/domain/user/dto/request/RoleRequest.java
  src/main/java/com/cone/cone/domain/user/dto/response/RoleResponse.java
  src/main/java/com/cone/cone/domain/user/entity/User.java
  src/main/java/com/cone/cone/domain/user/repository/UserRepository.java
  src/main/java/com/cone/cone/domain/user/service/AuthService.java
  src/main/java/com/cone/cone/global/annotation/SessionId.java
  src/main/java/com/cone/cone/global/annotation/SessionIdArgumentResolver.java
  src/main/java/com/cone/cone/global/config/WebConfig.java
  src/main/java/com/cone/cone/global/constant/SessionConstant.java
Labels: 🌱 Feat, ☁️ Refactor, 🍀 성은

#22 [FEAT] 멘티 프로필 조회 API 구현
  src/main/java/com/cone/cone/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/cone/cone/domain/user/code/MenteeSuccessCode.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeApi.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeController.java
  src/main/java/com/cone/cone/domain/user/controller/MentorController.java
  src/main/java/com/cone/cone/domain/user/dto/response/MenteeProfileResponse.java
  src/main/java/com/cone/cone/domain/user/entity/Mentee.java
  src/main/java/com/cone/cone/domain/user/entity/Mentor.java
  src/main/java/com/cone/cone/domain/user/repository/MenteeRepository.java
  src/main/java/com/cone/cone/domain/user/service/MenteeService.java
  src/main/java/com/cone/cone/domain/user/service/MenteeServiceImpl.java
Labels: 🌱 Feat, 🍀 성은

#26 [FIX] 소셜 로그인 예외 발생 시 CustomException으로 처리되지 않는 문제 해결 및 엔티티 수정사항 반영
  src/main/java/com/cone/cone/domain/mentorings/entity/Mentoring.java
  src/main/java/com/cone/cone/domain/user/dto/response/MenteeProfileResponse.java
  src/main/java/com/cone/cone/domain/user/dto/response/MentorProfileResponse.java
  src/main/java/com/cone/cone/domain/user/entity/Mentee.java
  src/main/java/com/cone/cone/domain/user/entity/Mentor.java
  src/main/java/com/cone/cone/domain/user/entity/User.java
  src/main/java/com/cone/cone/external/oauth/KakaoAuthService.java
  src/main/java/com/cone/cone/global/constant/DomainConstant.java
Labels: 🌱 Feat, 🍀 성은

#29 [FEAT] 실시간 채팅 및 시그널링 서버 구현
  build.gradle.kts
  src/main/java/com/cone/cone/domain/messages/entity/Message.java
  src/main/java/com/cone/cone/domain/messages/service/MessageServiceImpl.java
  src/main/java/com/cone/cone/domain/room/service/RoomServiceImpl.java
  src/main/java/com/cone/cone/external/oauth/OAuthPlatformServiceImpl.java
  src/main/java/com/cone/cone/external/socket/ChatFacade.java
  src/main/java/com/cone/cone/external/socket/ChatFacadeImpl.java
  src/main/java/com/cone/cone/external/socket/SocketService.java
  src/main/java/com/cone/cone/external/socket/SocketServiceImpl.java
  src/main/java/com/cone/cone/external/socket/constant/SocketIOEvent.java
  src/main/java/com/cone/cone/external/socket/controller/SocketIOController.java
  src/main/java/com/cone/cone/external/socket/dto/SignalingData.java
  src/main/java/com/cone/cone/external/socket/dto/SocketMessage.java
  src/main/java/com/cone/cone/global/config/SocketIOConfig.java
  src/main/java/com/cone/cone/global/runner/SocketIOServerRunner.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
Labels: 🌱 Feat, 🌱 송목

#30 [FEAT] 멘토링 신청 API 구현
  .gitignore
  src/main/java/com/cone/cone/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/cone/cone/domain/auth/service/SessionService.java
  src/main/java/com/cone/cone/domain/auth/service/SessionServiceImpl.java
  src/main/java/com/cone/cone/domain/mentorings/code/MentoringSuccessCode.java
  src/main/java/com/cone/cone/domain/mentorings/controller/MentoringApi.java
  src/main/java/com/cone/cone/domain/mentorings/controller/MentoringController.java
  src/main/java/com/cone/cone/domain/mentorings/dto/request/MentoringRequest.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MentoringIdResponse.java
  src/main/java/com/cone/cone/domain/mentorings/entity/Mentoring.java
  src/main/java/com/cone/cone/domain/mentorings/repository/MentoringRepository.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringService.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringServiceImpl.java
  src/main/java/com/cone/cone/domain/messages/service/MessageServiceImpl.java
  src/main/java/com/cone/cone/domain/room/entity/Room.java
  src/main/java/com/cone/cone/domain/room/repository/RoomRepository.java
  src/main/java/com/cone/cone/domain/room/service/RoomServiceImpl.java
  src/main/java/com/cone/cone/domain/user/code/MenteeExceptionCode.java
  src/main/java/com/cone/cone/domain/user/code/MentorExceptionCode.java
  src/main/java/com/cone/cone/domain/user/entity/User.java
  src/main/java/com/cone/cone/domain/user/repository/MenteeRepository.java
  src/main/java/com/cone/cone/domain/user/repository/MentorRepository.java
Labels: 🌱 Feat, 🍀 성은

#32 [FEAT] profile 환경변수로 관리
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: 🌱 Feat, ☁️ Refactor

#34 [FEAT] 멘티 입장에서의 멘토링 현황 리스트 조회 API 구현
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MenteeMentoringResponse.java
  src/main/java/com/cone/cone/domain/mentorings/entity/Mentoring.java
  src/main/java/com/cone/cone/domain/mentorings/repository/MentoringRepository.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringService.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringServiceImpl.java
  src/main/java/com/cone/cone/domain/user/code/MenteeSuccessCode.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeApi.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeController.java
Labels: 🌱 Feat, 🍀 성은

#39 [FIX] CORS 에러
  src/main/java/com/cone/cone/global/config/SocketIOConfig.java
  src/main/java/com/cone/cone/global/config/WebConfig.java
Labels: 🎈 Fix, 🌱 송목

#42 [FEAT] 내정보 조회 API 구현
  src/main/java/com/cone/cone/domain/auth/code/AuthSuccessCode.java
  src/main/java/com/cone/cone/domain/auth/controller/AuthApi.java
  src/main/java/com/cone/cone/domain/auth/controller/AuthController.java
  src/main/java/com/cone/cone/domain/auth/service/AuthService.java
  src/main/java/com/cone/cone/domain/auth/service/AuthServiceImpl.java
Labels: 🌱 Feat, 🌱 송목

#45 [FIX] Origins에 Https 경로 추가 및 socialLogin 경로도 allowCredential에 포함
  src/main/java/com/cone/cone/global/config/WebConfig.java
Labels: 🎈 Fix, 🍀 성은

#49 [FIX] same-site: lax로 변경
  src/main/resources/application-local.yml
Labels: 🎈 Fix, 🍀 성은

#56 [FEAT] 멘토링 수정 API 구현
  src/main/java/com/cone/cone/domain/mentorings/code/MentoringExceptionCode.java
  src/main/java/com/cone/cone/domain/mentorings/code/MentoringSuccessCode.java
  src/main/java/com/cone/cone/domain/mentorings/controller/MentoringApi.java
  src/main/java/com/cone/cone/domain/mentorings/controller/MentoringController.java
  src/main/java/com/cone/cone/domain/mentorings/dto/request/MentoringBookingRequest.java
  src/main/java/com/cone/cone/domain/mentorings/dto/request/MentoringRejectRequest.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MentoringTimeResponse.java
  src/main/java/com/cone/cone/domain/mentorings/entity/Mentoring.java
  src/main/java/com/cone/cone/domain/mentorings/repository/MentoringRepository.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringService.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringServiceImpl.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringServiceRecordServiceImpl.java
  src/main/java/com/cone/cone/domain/user/code/MentorSuccessCode.java
  src/main/java/com/cone/cone/domain/user/controller/MentorController.java
  src/main/java/com/cone/cone/domain/user/entity/User.java
  src/main/java/com/cone/cone/global/base/BaseTime.java
Labels: 🌱 Feat, 🌱 송목

#60 [FEAT] 메시지 타입 추가
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringServiceImpl.java
  src/main/java/com/cone/cone/domain/messages/constant/MessageConstant.java
  src/main/java/com/cone/cone/domain/messages/dto/MessageSimpleResponse.java
  src/main/java/com/cone/cone/domain/messages/entity/Message.java
  src/main/java/com/cone/cone/domain/messages/entity/type/MessageType.java
  src/main/java/com/cone/cone/domain/messages/service/MessageService.java
  src/main/java/com/cone/cone/domain/messages/service/MessageServiceImpl.java
  src/main/java/com/cone/cone/domain/room/controller/RoomApi.java
  src/main/java/com/cone/cone/domain/room/controller/RoomController.java
  src/main/java/com/cone/cone/domain/room/entity/Room.java
  src/main/java/com/cone/cone/domain/room/repository/RoomRepository.java
  src/main/java/com/cone/cone/domain/room/service/RoomServiceImpl.java
  src/main/java/com/cone/cone/domain/user/constant/UserConstant.java
  src/main/java/com/cone/cone/external/socket/ChatFacade.java
  src/main/java/com/cone/cone/external/socket/ChatFacadeImpl.java
  src/main/java/com/cone/cone/external/socket/SocketService.java
  src/main/java/com/cone/cone/external/socket/SocketServiceImpl.java
  src/main/java/com/cone/cone/external/socket/constant/SocketIOEvent.java
  src/main/java/com/cone/cone/external/socket/controller/SocketIOController.java
  src/main/java/com/cone/cone/external/socket/dto/SocketMessage.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/socket.yml
Labels: 🌱 Feat, ☁️ Refactor, 🌱 송목

#61 [CHORE] 코드 리팩터링
  src/main/java/com/cone/cone/domain/auth/code/AuthSuccessCode.java
  src/main/java/com/cone/cone/domain/auth/controller/AuthApi.java
  src/main/java/com/cone/cone/domain/auth/controller/AuthController.java
  src/main/java/com/cone/cone/domain/auth/service/AuthService.java
  src/main/java/com/cone/cone/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/cone/cone/domain/auth/service/SessionServiceImpl.java
  src/main/java/com/cone/cone/domain/mentorings/code/MentoringExceptionCode.java
  src/main/java/com/cone/cone/domain/mentorings/code/MentoringSuccessCode.java
  src/main/java/com/cone/cone/domain/mentorings/controller/MentoringApi.java
  src/main/java/com/cone/cone/domain/mentorings/controller/MentoringController.java
  src/main/java/com/cone/cone/domain/mentorings/dto/request/MentoringBookingRequest.java
  src/main/java/com/cone/cone/domain/mentorings/dto/request/MentoringRecordRequest.java
  src/main/java/com/cone/cone/domain/mentorings/dto/request/MentoringRejectRequest.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MenteeMentoringResponse.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MentorMentoringResponse.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MentoringForMenteeResponse.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MentoringForMentorResponse.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MentoringIdResponse.java
  src/main/java/com/cone/cone/domain/mentorings/dto/response/MentoringTimeResponse.java
  src/main/java/com/cone/cone/domain/mentorings/repository/MentoringRepository.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringService.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringServiceImpl.java
  src/main/java/com/cone/cone/domain/mentorings/service/MentoringServiceRecordServiceImpl.java
  src/main/java/com/cone/cone/domain/messages/dto/MessageResponse.java
  src/main/java/com/cone/cone/domain/messages/dto/MessageSimpleResponse.java
  src/main/java/com/cone/cone/domain/messages/service/MessageService.java
  src/main/java/com/cone/cone/domain/messages/service/MessageServiceImpl.java
  src/main/java/com/cone/cone/domain/room/controller/RoomApi.java
  src/main/java/com/cone/cone/domain/room/controller/RoomController.java
  src/main/java/com/cone/cone/domain/room/dto/RoomResponse.java
  src/main/java/com/cone/cone/domain/room/entity/Room.java
  src/main/java/com/cone/cone/domain/room/repository/RoomRepository.java
  src/main/java/com/cone/cone/domain/room/service/RoomService.java
  src/main/java/com/cone/cone/domain/room/service/RoomServiceImpl.java
  src/main/java/com/cone/cone/domain/user/code/MenteeExceptionCode.java
  src/main/java/com/cone/cone/domain/user/code/MentorExceptionCode.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeApi.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeController.java
  src/main/java/com/cone/cone/domain/user/controller/MentorApi.java
  src/main/java/com/cone/cone/domain/user/controller/MentorController.java
  src/main/java/com/cone/cone/domain/user/dto/request/LoginRequest.java
  src/main/java/com/cone/cone/domain/user/dto/response/MenteeProfileResponse.java
  src/main/java/com/cone/cone/domain/user/dto/response/MenteeResponse.java
  src/main/java/com/cone/cone/domain/user/dto/response/MentorProfileResponse.java
  src/main/java/com/cone/cone/domain/user/dto/response/MentorResponse.java
  src/main/java/com/cone/cone/domain/user/dto/response/UserResponse.java
  src/main/java/com/cone/cone/domain/user/entity/AuditStatus.java
  src/main/java/com/cone/cone/domain/user/entity/Mentee.java
  src/main/java/com/cone/cone/domain/user/entity/Mentor.java
  src/main/java/com/cone/cone/domain/user/entity/MentorStatus.java
  src/main/java/com/cone/cone/domain/user/entity/User.java
  src/main/java/com/cone/cone/domain/user/repository/MenteeRepository.java
  src/main/java/com/cone/cone/domain/user/repository/MentorRepository.java
  src/main/java/com/cone/cone/domain/user/service/MenteeService.java
  src/main/java/com/cone/cone/domain/user/service/MenteeServiceImpl.java
  src/main/java/com/cone/cone/domain/user/service/MentorService.java
  src/main/java/com/cone/cone/domain/user/service/MentorServiceImpl.java
  src/main/java/com/cone/cone/external/code/ClientExceptionCode.java
  src/main/java/com/cone/cone/external/oauth/dto/UserInfoResponse.java
  src/main/java/com/cone/cone/global/config/WebConfig.java
Labels: ☁️ Refactor, ☂️ Chore, 🌱 송목

#63 [FEAT] Disconnection 알림, Response Dto 변경
  src/main/java/com/cone/cone/domain/room/dto/RoomForMenteeResponse.java
  src/main/java/com/cone/cone/domain/room/dto/RoomForMentorResponse.java
  src/main/java/com/cone/cone/domain/room/dto/RoomResponse.java
  src/main/java/com/cone/cone/domain/room/service/RoomService.java
  src/main/java/com/cone/cone/domain/room/service/RoomServiceImpl.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeApi.java
  src/main/java/com/cone/cone/domain/user/controller/MenteeController.java
  src/main/java/com/cone/cone/domain/user/controller/MentorApi.java
  src/main/java/com/cone/cone/domain/user/controller/MentorController.java
  src/main/java/com/cone/cone/external/socket/constant/SocketIOEvent.java
  src/main/java/com/cone/cone/external/socket/controller/SocketIOController.java
Labels: 🌱 Feat, 🌱 송목
